-- Day 22: the company tree, approvals that follow it, and the client's two
-- changes to HR that waited for it.

-- 1. The owner mark and Settings → Approvals (generated by migration:new).

-- CreateEnum
CREATE TYPE "LeaveBackupApprover" AS ENUM ('super_admin', 'next_up', 'none');

-- CreateEnum
CREATE TYPE "LeaveReversalBy" AS ENUM ('manager_or_super_admin', 'super_admin_only');

-- AlterTable
ALTER TABLE "Organization" ADD COLUMN     "leaveBackup" "LeaveBackupApprover" NOT NULL DEFAULT 'super_admin',
ADD COLUMN     "leaveNoManagerApproverId" TEXT,
ADD COLUMN     "leaveReversal" "LeaveReversalBy" NOT NULL DEFAULT 'manager_or_super_admin',
ADD COLUMN     "ownerEmployeeId" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Organization_ownerEmployeeId_key" ON "Organization"("ownerEmployeeId");

-- AddForeignKey
ALTER TABLE "Organization" ADD CONSTRAINT "Organization_ownerEmployeeId_fkey" FOREIGN KEY ("ownerEmployeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Organization" ADD CONSTRAINT "Organization_leaveNoManagerApproverId_fkey" FOREIGN KEY ("leaveNoManagerApproverId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 2. HR rows still exactly at the Day 21 default take the new one: no leave
--    approving (the tree decides), and salaries seen for everybody except the
--    people above them. A company that changed its HR role keeps its change.
--    Compared BEFORE step 3 takes `leave:approve` off every role.
UPDATE "Role"
SET "permissions" = ARRAY['dashboard:read', 'employee:read', 'employee:create', 'employee:update', 'employee:identity:read', 'employee:compensation:read', 'attendance:read', 'attendance:punch', 'attendance:mark', 'attendance:update', 'attendance:delete', 'leave:read', 'leave:apply', 'leave:balance:manage', 'leave:type:manage', 'holiday:manage', 'payroll:entry:manage', 'document:read', 'document:upload', 'document:verify', 'document:company:read', 'document:company:manage', 'document:type:manage', 'payslip:read', 'notification:read']::text[],
    "scopes" = '{"employee":"ORGANIZATION","compensation":"ORGANIZATION_EXCEPT_ABOVE","attendance":"ORGANIZATION","leave":"ORGANIZATION","payslip":"SELF","document":"ORGANIZATION"}'::jsonb,
    "updatedAt" = now()
WHERE "key" = 'hr'
  AND "builtIn" = true
  AND (SELECT array_agg(p ORDER BY p) FROM unnest("permissions") AS p)
    = (SELECT array_agg(p ORDER BY p) FROM unnest(ARRAY['dashboard:read', 'employee:read', 'employee:create', 'employee:update', 'employee:identity:read', 'attendance:read', 'attendance:punch', 'attendance:mark', 'attendance:update', 'attendance:delete', 'leave:read', 'leave:apply', 'leave:approve', 'leave:balance:manage', 'leave:type:manage', 'holiday:manage', 'payroll:entry:manage', 'document:read', 'document:upload', 'document:verify', 'document:company:read', 'document:company:manage', 'document:type:manage', 'payslip:read', 'notification:read']::text[]) AS p)
  AND "scopes" = '{"employee":"ORGANIZATION","compensation":"SELF","attendance":"ORGANIZATION","leave":"ORGANIZATION","payslip":"SELF","document":"ORGANIZATION"}'::jsonb;

UPDATE "Role"
SET "description" = 'Runs people operations day to day: employees, attendance, documents, holidays and monthly incentives. Sees all leave, gives the yearly leave and corrects balances. Sees salaries, except those of the people above them.'
WHERE "key" = 'hr' AND "builtIn" = true
  AND "description" = 'Runs people operations day to day: employees, attendance, leave, documents, holidays and monthly incentives.';

-- 3. `leave:approve` no longer exists: approving follows the company tree,
--    whatever the approver's role. Taken off every role, custom ones included
--    (the server would ignore it anyway — unknown permissions are dropped).
UPDATE "Role"
SET "permissions" = array_remove("permissions", 'leave:approve'), "updatedAt" = now()
WHERE 'leave:approve' = ANY ("permissions");

UPDATE "Role"
SET "description" = 'Leads a team: sees the team''s attendance and leave.'
WHERE "key" = 'manager' AND "builtIn" = true
  AND "description" = 'Leads a team: sees the team''s attendance and leave, and approves the team''s leave.';

-- 4. The built-in roles a NEW company gets. GENERATED by
--    `npx tsx scripts/roleSeedSql.ts` from defaultRoles.ts; roles.test.ts
--    fails if a new company's roles ever differ from that file.
CREATE OR REPLACE FUNCTION ems_seed_default_roles(org_id TEXT) RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  id_super_admin TEXT := gen_random_uuid()::text;
  id_admin TEXT := gen_random_uuid()::text;
  id_hr TEXT := gen_random_uuid()::text;
  id_accounts TEXT := gen_random_uuid()::text;
  id_manager TEXT := gen_random_uuid()::text;
  id_rm TEXT := gen_random_uuid()::text;
  id_employee TEXT := gen_random_uuid()::text;
BEGIN
  INSERT INTO "Role" ("id", "organizationId", "key", "name", "description", "parentId", "builtIn", "locked", "permissions", "scopes", "updatedAt") VALUES
    (id_super_admin, org_id, 'super_admin', 'Super Admin', 'The owner of the system. Everything, including approving the payroll, reports, the audit log, settings, users and roles.', NULL, true, true, ARRAY['dashboard:read', 'employee:read', 'employee:create', 'employee:update', 'employee:delete', 'employee:compensation:read', 'employee:bank:read', 'employee:bank:manage', 'employee:identity:read', 'attendance:read', 'attendance:punch', 'attendance:mark', 'attendance:update', 'attendance:delete', 'leave:read', 'leave:apply', 'leave:balance:manage', 'leave:type:manage', 'holiday:manage', 'payroll:structure:read', 'payroll:structure:manage', 'payroll:run:create', 'payroll:run:approve', 'payroll:entry:manage', 'payslip:read', 'document:read', 'document:upload', 'document:verify', 'document:company:read', 'document:company:manage', 'document:type:manage', 'notification:read', 'report:read', 'settings:read', 'settings:update', 'user:invite', 'user:status:update', 'user:delete', 'membership:role:assign', 'audit:read', 'role:manage']::text[], '{"employee":"ORGANIZATION","compensation":"ORGANIZATION","attendance":"ORGANIZATION","leave":"ORGANIZATION","payslip":"ORGANIZATION","document":"ORGANIZATION"}'::jsonb, now()),
    (id_admin, org_id, 'admin', 'Admin', 'Looks after employee records and documents.', id_super_admin, true, false, ARRAY['dashboard:read', 'employee:read', 'employee:create', 'employee:update', 'leave:type:manage', 'document:read', 'document:upload', 'document:verify', 'document:company:read', 'document:company:manage', 'document:type:manage', 'payslip:read', 'notification:read']::text[], '{"employee":"ORGANIZATION","compensation":"SELF","attendance":"SELF","leave":"SELF","payslip":"SELF","document":"ORGANIZATION"}'::jsonb, now()),
    (id_hr, org_id, 'hr', 'HR', 'Runs people operations day to day: employees, attendance, documents, holidays and monthly incentives. Sees all leave, gives the yearly leave and corrects balances. Sees salaries, except those of the people above them.', id_super_admin, true, false, ARRAY['dashboard:read', 'employee:read', 'employee:create', 'employee:update', 'employee:identity:read', 'employee:compensation:read', 'attendance:read', 'attendance:punch', 'attendance:mark', 'attendance:update', 'attendance:delete', 'leave:read', 'leave:apply', 'leave:balance:manage', 'leave:type:manage', 'holiday:manage', 'payroll:entry:manage', 'document:read', 'document:upload', 'document:verify', 'document:company:read', 'document:company:manage', 'document:type:manage', 'payslip:read', 'notification:read']::text[], '{"employee":"ORGANIZATION","compensation":"ORGANIZATION_EXCEPT_ABOVE","attendance":"ORGANIZATION","leave":"ORGANIZATION","payslip":"SELF","document":"ORGANIZATION"}'::jsonb, now()),
    (id_accounts, org_id, 'accounts', 'Accounts', 'Salaries and payroll: salary structures, the monthly payroll, bank accounts and the bank transfer file.', id_super_admin, true, false, ARRAY['dashboard:read', 'employee:compensation:read', 'employee:bank:read', 'employee:bank:manage', 'payroll:structure:read', 'payroll:structure:manage', 'payroll:run:create', 'payroll:entry:manage', 'payslip:read', 'document:company:read', 'notification:read']::text[], '{"employee":"ORGANIZATION","compensation":"ORGANIZATION","attendance":"SELF","leave":"SELF","payslip":"ORGANIZATION","document":"SELF"}'::jsonb, now()),
    (id_manager, org_id, 'manager', 'Manager', 'Leads a team: sees the team''s attendance and leave.', id_hr, true, false, ARRAY['dashboard:read', 'employee:read', 'attendance:read', 'attendance:punch', 'leave:read', 'leave:apply', 'payslip:read', 'document:company:read', 'notification:read']::text[], '{"employee":"ORGANIZATION","compensation":"SELF","attendance":"DIRECT_REPORTS","leave":"DIRECT_REPORTS","payslip":"SELF","document":"SELF"}'::jsonb, now()),
    (id_rm, org_id, 'rm', 'Reporting Manager', 'The same as Manager, under a different title.', id_manager, true, false, ARRAY['dashboard:read', 'employee:read', 'attendance:read', 'attendance:punch', 'leave:read', 'leave:apply', 'payslip:read', 'document:company:read', 'notification:read']::text[], '{"employee":"ORGANIZATION","compensation":"SELF","attendance":"DIRECT_REPORTS","leave":"DIRECT_REPORTS","payslip":"SELF","document":"SELF"}'::jsonb, now()),
    (id_employee, org_id, 'employee', 'Employee', 'Their own attendance, leave, payslips, documents and bank account.', id_rm, true, false, ARRAY['dashboard:read', 'attendance:read', 'attendance:punch', 'leave:read', 'leave:apply', 'document:read', 'document:upload', 'payslip:read', 'document:company:read', 'notification:read']::text[], '{"employee":"SELF","compensation":"SELF","attendance":"SELF","leave":"SELF","payslip":"SELF","document":"SELF"}'::jsonb, now());
END
$$;
